const ACTION_TYPES = {
    GET_HEROES_ACTION: 'GET_HEROES_ACTION',
    GET_HEROES_REQUEST: 'GET_HEROES_REQUEST',
    GET_HEROES_SUCCESS: 'GET_HEROES_SUCCESS',
    GET_HEROES_ERROR: 'GET_HEROES_ERROR',
}

export default ACTION_TYPES;