const ACTION_TYPES = {
    GET_HEROES_ACTION: 'GET_HEROES_ACTION',
    GET_HEROES_REQUEST: 'GET_HEROES_REQUEST',
    GET_HEROES_SUCCESS: 'GET_HEROES_SUCCESS',
    GET_HEROES_ERROR: 'GET_HEROES_ERROR',

    GET_POWERS_ACTION: 'GET_POWERS_ACTION',
    GET_POWERS_REQUEST: 'GET_POWERS_REQUEST',
    GET_POWERS_SUCCESS: 'GET_POWERS_SUCCESS',
    GET_POWERS_ERROR: 'GET_POWERS_ERROR',
}

export default ACTION_TYPES;